col_types = cols(.default = col_character(),
                 LMK_KEY = col_double(),
                 BUILDING_REFERENCE_NUMBER = col_double(),
                 CURRENT_ENERGY_RATING	= col_factor(c("A","B","C","D","E","F","G","INVALID!"), TRUE), 
                 POTENTIAL_ENERGY_RATING = col_factor(c("A","B","C","D","E","F","G","INVALID!"), TRUE),
                 CURRENT_ENERGY_EFFICIENCY = col_integer(),
                 POTENTIAL_ENERGY_EFFICIENCY = col_integer(),
                 PROPERTY_TYPE = col_factor(c("Flat","House","Maisonette","Bungalow","Park home"), FALSE),
                 BUILT_FORM = col_factor(c("Detached","Semi-Detached","Mid-Terrace",
                                           "Enclosed Mid-Terrace","NO DATA!",
                                           "End-Terrace","Enclosed End-Terrace" ), FALSE),
                 INSPECTION_DATE = col_date(),
                 #LOCAL_AUTHORITY = col_factor(),
                 CONSTITUENCY = col_factor(),
                 COUNTY = col_factor(),
                 LODGEMENT_DATE = col_date(),
                 ENVIRONMENT_IMPACT_CURRENT = col_integer(),
                 ENVIRONMENT_IMPACT_POTENTIAL = col_integer(),
                 ENERGY_CONSUMPTION_CURRENT = col_integer(),
                 ENERGY_CONSUMPTION_POTENTIAL = col_double(),
                 CO2_EMISSIONS_CURRENT = col_double(),
                 CO2_EMISS_CURR_PER_FLOOR_AREA = col_double(),
                 CO2_EMISSIONS_POTENTIAL = col_double(),
                 LIGHTING_COST_CURRENT = col_double(),
                 LIGHTING_COST_POTENTIAL = col_double(),
                 HEATING_COST_CURRENT = col_double(),
                 HEATING_COST_POTENTIAL = col_double(),
                 HOT_WATER_COST_CURRENT = col_double(),
                 HOT_WATER_COST_POTENTIAL = col_double(),
                 TOTAL_FLOOR_AREA = col_double(),
                 ENERGY_TARIFF = col_factor(c("standard tariff","24 hour","off-peak 7 hour","Single",
                                              "dual","Unknown","dual (24 hour)","off-peak 10 hour",
                                              "off-peak 18 hour","NO DATA!","INVALID!"), FALSE),
                 MAINS_GAS_FLAG = col_factor(c("Y","N"), FALSE),
                 FLAT_TOP_STOREY = col_factor(c("Y","N"), FALSE),
                 FLAT_STOREY_COUNT	= col_integer(),
                 #MAIN_HEATING_CONTROLS = col_integer(),
                 MULTI_GLAZE_PROPORTION = col_integer(),
                 GLAZED_TYPE	= col_factor(c("NO DATA!",
                                            "INVALID!",
                                            "double glazing installed before 2002",
                                            "double glazing installed during or after 2002",
                                            "double glazing, unknown install date",
                                            "not defined",
                                            "single glazing",
                                            "secondary glazing",
                                            "triple glazing",
                                            "double, known data",
                                            "triple, known data"), FALSE),
                 
                 GLAZED_AREA	= col_factor(c("Much Less Than Typical","Less Than Typical","Normal",
                                            "More Than Typical","Much More Than Typical","NO DATA!"), TRUE),
                 EXTENSION_COUNT = col_integer(),
                 NUMBER_HABITABLE_ROOMS = col_integer(),
                 NUMBER_HEATED_ROOMS = col_integer(),
                 LOW_ENERGY_LIGHTING = col_integer(),
                 NUMBER_OPEN_FIREPLACES = col_integer(),
                 HOT_WATER_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 HOT_WATER_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 FLOOR_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","NO DATA!","N/A"), TRUE),
                 FLOOR_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","NO DATA!","N/A"), TRUE),
                 
                 WINDOWS_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 WINDOWS_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 WALLS_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 WALLS_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 ROOF_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 ROOF_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 MAINHEAT_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 MAINHEAT_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 MAINHEATC_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 MAINHEATC_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 LIGHTING_ENERGY_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 LIGHTING_ENV_EFF = col_factor(c("Very Good","Good","Average","Poor","Very Poor","N/A"), TRUE),
                 WIND_TURBINE_COUNT = col_integer(),
                 HEAT_LOSS_CORRIDOOR = col_factor(c("NO DATA!","unheated corridor","heated corridor","no corridor"), FALSE),
                 UNHEATED_CORRIDOR_LENGTH = col_double(),
                 FLOOR_HEIGHT = col_double(),
                 PHOTO_SUPPLY = col_integer(),
                 SOLAR_WATER_HEATING_FLAG = col_factor(c("N","Y"), FALSE),
                 MECHANICAL_VENTILATION = col_factor(c("NO DATA!","natural","mechanical, extract only","mechanical, supply and extract"), FALSE)
)